# version is obsolete
#version: '3.9'

# use extension fields to define a global log configuration to use in multiple services via an alias (*) to the anchor (&)
# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-logging: &default-logging
  options:
    max-size: '20m'
    max-file: '5'
  driver: json-file

volumes:
  todo_local_postgres_data: {}
  todo_local_postgres_data_backups: {}

services:
  todo_django: &django
    logging: *default-logging
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: todo_local_django
    container_name: todo_local_django
    depends_on:
      - postgres
      - todo_mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '${TODO_PORT:-8400}:8400'
    command: /start

  postgres:
    logging: *default-logging
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: todo_production_postgres
    container_name: todo_local_postgres
    volumes:
      - todo_local_postgres_data:/var/lib/postgresql/data
      - todo_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '${FORWARD_POSTGRES_PORT:-5432}:5432'
  todo_docs:
    logging: *default-logging
    image: todo_local_docs
    container_name: todo_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./todo:/app/todo:z
    ports:
      - '${DOCS_PORT:-9400}:9400'
    command: /start-docs

  todo_mailpit:
    logging: *default-logging
    image: 'axllent/mailpit:latest'
    container_name: todo_local_mailpit
    ports:
        - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
  todo_pma:
      image: phpmyadmin/phpmyadmin
      container_name: todo_pma
      environment:
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_ROOT_HOST: '%'
          PMA_HOST: todo_db
          UPLOAD_LIMIT: 300M
      depends_on:
          - postgres
      ports:
          - '${FORWARD_PMA_PORT:-8306}:80'
